### ISSUE TITLE
Group GitHub Collaboration

### ISSUE THREAD

**Issue by jche** [AmherstCollege/STAT370-Spring16#1]
In theory, it makes sense for our groups to use GitHub for our problem set solutions, right? It would enable all of us to work on the same .Rmd file at the same time.

How do we do this? I've currently set up a public repo with my solution .Rmd in it. I can pull/push changes from/to this repo. My group members can clone the repo (like we did in class) and make edits, but don't seem to have the option to push changes or even create a pull request from the RStudio interface. They can do so from the repo page on GitHub, but this is inconvenient. How can I either: 
**1)** Give my group members full permission to push changes, or 
**2)** Let them make pull requests from within RStudio?

**Comment by nicholasjhorton** [comment]
That's a great idea, and exactly where I'm planning for later in the semester.  For now, I would hold off (as we'll be changing groups next week).

**Comment by nicholasjhorton** [comment]
One overall comment on the use of github for group assignments: you don't want to include the Rproj file or the .gitignore file in the repository.  Please let me know if you've done this and I can help to fix it.
