### ISSUE TITLE
Determining Efficiency of Estimators

### ISSUE THREAD

**Issue by akim17** [AmherstCollege/STAT370-Spring16#11]
In section 8.7, Rice introduces the idea of efficiency to determine the best estimator for a population parameter. When calculating the efficiency of one estimator to another, are we just comparing, say, the method of moments estimator to the MLE estimator? Rice also mentions that this efficiency term is most helpful when comparing two unbiased estimators, or two estimators with the same bias. Is there any way to compare two estimators with different biases?

**Comment by nicholasjhorton** [comment]
If an estimator is biased, do we really care so much about whether it is efficient (lower variance?)  We will see this question again in terms of the mean squared error: a measure that includes both variance and bias (see Rice page 136).
