### ISSUE TITLE
Bootstrapping in R

### ISSUE THREAD

**Issue by steichman18** [AmherstCollege/STAT370-Spring16#14]
I recall you mentioned at some point in class or a coaching session that you don't like to use the bootstrap function in R. I was wondering what is wrong with it, and what is an alternative. Is the best method just to write our own function that will sample with replacement from the existing sample distribution?

**Comment by nicholasjhorton** [comment]
I have no particular problems with the "boot" package in R (https://cran.r-project.org/web/packages/boot/index.html), though I find some aspects of its interface to be confusing.

For many applications, the combination of mosaic::do() and mosaic::resample() may do the trick.  The vignette https://cran.r-project.org/web/packages/mosaic/vignettes/Resampling.pdf may suffice.  Tim Hesterberg has a list of other options http://www.timhesterberg.net/bootstrap#TOC-S-and-R-software
