### ISSUE TITLE
Consistent and unbiased estimates

### ISSUE THREAD

**Issue by ajavaid17** [AmherstCollege/STAT370-Spring16#15]
Rice mentions how an estimated parameter is said to be consistent as it approaches the population estimate as sample size tends to infinity (pg. 226). Is this concept a derivation of the notion of an unbiased estimate? Or is the size element in consistent estimates differs it from an unbiased estimate?

**Comment by nicholasjhorton** [comment]
Consistency (defined formally on pages 266-267) says that an estimator approaches \theta as the sample size goes to infinity.  It means that it is asymptotically unbiased and that the variance goes to 0 as n goes to infinity.
