### ISSUE TITLE
Calculate confidence interval for the trimmed mean

### ISSUE THREAD

**Issue by letrangg** [AmherstCollege/STAT370-Spring16#16]
When calculating the standard error for the trimmed mean, is it appropriate to use the standard deviation of the whole sample divided by the square root of the sample size? Will this guarantee correctness?

**Comment by nicholasjhorton** [comment]
Be careful with inference for trimmed means: you can't just apply the usual estimates for the mean (the same is true for medians).  

The following site provides some guidance about an analytic approach:
http://www.itl.nist.gov/div898/software/dataplot/refman1/auxillar/trimmecl.htm

All students are encouraged to carefully read and review Rice problem 10.10 (particularly the last part) prior to the presentations on Monday.
