### ISSUE TITLE
Rice 10.10 - Finding the expected value of the k-th order statistic 

### ISSUE THREAD

**Issue by letrangg** [AmherstCollege/STAT370-Spring16#18]
I'm reviewing the answer for problem set 3, and I'm a bit stuck in 10.10a (finding the mean and variance of k-th order statistic in the case of uniform distribution and the general case). How did the first line transform into the second line? 

<img width="438" alt="screen shot 2016-02-23 at 14 47 15" src="https://cloud.githubusercontent.com/assets/10510160/13264491/77aa008a-da3c-11e5-8fd4-54e65c20f31a.png">

Rice's method was very smart, and I'm curious how are these results useful? Is it used to evaluate the robustness of the median?

**Comment by stephramos17** [comment]
Hi Trang!
In answer to your question, you're right in being skeptical by this step. To first solve for the constant I used the fact that gamma(n+1)=n*gamma(n) and gamma(n)=(n-1)! _not _ gamma(n)=(n+1)! (you can find Rice talk about this on p.68).  In terms of the integral, to find the integral shown in the first line, I just used wolfram alpha to solve it (you can see this here--->http://www.wolframalpha.com/input/?i=integral+from+0+to+1+of+x%5Ek+(1-x)%5E(n-k)+dx). However from some of my search on the matter, one way one could solve for this integral is by somehow applying the definition of the gamma function (p.53). 

In terms of it's usefulness I am once again in complete agreement with you. I too was left wondering why we had to solve for the mean and variance of X_k when what we needed to use to solve part (d) was the mean and variance of the Y_k, the k-th order statistic (given in b). This is why we did not include these derivations to answer our first questions and just left this as part of our appendix . However, maybe we're both missing something and maybe Nick or someone else from our class can shed some light on the matter?

Anyway, I hope this was of help to you!
