### ISSUE TITLE
Scatterplot Matrix 

### ISSUE THREAD

**Issue by chaley17** [AmherstCollege/STAT370-Spring16#2]
Rice 10.7 (pg 407), as well as in class, used a scatterplot matrix, and I was wondering if these plots would be considered a good "summary" of data? While they encompass many variables, I'm not sure if they tell you everything you'd want to know about the data.

**Comment by nicholasjhorton** [comment]
They are sometimes hard to see detail (particularly if there are many variables) but I often find them useful for exploratory analyses.
