### ISSUE TITLE
GOF test for stat lab 4.16

### ISSUE THREAD

**Issue by steichman18** [AmherstCollege/STAT370-Spring16#22]
In testing the ad.test, it works for normal and not for poisson, so it might only check for normality.

**Comment by nicholasjhorton** [comment]
That was my impression about ad.test(): thanks for confirming.

There are other approaches to GOF testing (see for example http://stats.stackexchange.com/questions/1174/how-can-i-test-if-given-samples-are-taken-from-a-poisson-distribution).  My suggestion would be conduct a Chisquare GOF test for the observed vs. expected counts (where you group the rarer bins).
