### ISSUE TITLE
Rice Chapter 8

### ISSUE THREAD

**Issue by mowen17** [AmherstCollege/STAT370-Spring16#3]
Throughout Chapter 8 of Rice, I noticed that in a lot of theorems it says "under smoothness conditions". I was wondering what exactly "smoothness conditions" are, and why it is important to assume this for many of the theorems in Chapter 8.

**Comment by nicholasjhorton** [comment]
My earlier comment addressed this (there's a file on Moodle that lays out the key conditions).
