### ISSUE TITLE
Functions in R Involving GitHub

### ISSUE THREAD

**Issue by llee17** [AmherstCollege/STAT370-Spring16#5]
After copying a repository from GitHub to R, the part of our R (on the Amherst server) interface now contains a new tab (where the History and Environment tabs are located.) I wanted to inquire more about what functions like "Diff," "Commit," "Push," and "Pull" are. Additionally, I wanted to know about the compatibility between GitHub on the local desktop version of RStudio.

**Comment by nicholasjhorton** [comment]
The new "Git" tab that you see when you open up a project using version control with git lets you sync up your copy of the repository with the version at github.com.

Soon I'll show you how to add or modify a file in your repository, "Commit" and document those changes, then push them out to github.

For the existing repository that you cloned (STAT370-Spring16), you should do a "pull" and see the new files that I added yesterday.

It's straightforward to install github on your computer if you are running a local version of RStudio.  The best way to proceed is to create a new project using version control, select git, and follow the directions to install the git software if it's not already been installed.  I'd be happy to assist with this process (but there's no rush in doing so).
