### ISSUE TITLE
Resampling

### ISSUE THREAD

**Issue by calebki94** [AmherstCollege/STAT370-Spring16#7]
So far we've only talked about bootstrapping as a method of resampling. I was wondering what advantages bootstrapping presents over other resampling methods such as jackknifing and subsampling. What are the different situations where one method is better than the other?

**Comment by nicholasjhorton** [comment]
In a nutshell, you can think of the bootstrap as a more flexible jackknife (with all possible samples not just leave-k out).  Before we had faster computers, jackknifing was the only feasible alternative, but now we can use the more general approach.

See http://stats.stackexchange.com/questions/21023/bootstrap-vs-jackknife for a related discussion with other links.
