### ISSUE TITLE
Rice Section 8.6

### ISSUE THREAD

**Issue by mmanley18** [AmherstCollege/STAT370-Spring16#8]
In this section Rice discusses the Bayesian approach to parameter estimation and runs us through examples which apply this method. I was wondering if there was any particular advantage or disadvantage to using this technique when compared to that which is discussed in section 8.3.

**Comment by nicholasjhorton** [comment]
The Bayesian approach is different: it complements rather than duplicates the methods of 8.4 and 8.5.  There's a nice overview on Wikipedia: https://en.wikipedia.org/wiki/Bayesian_inference
