### ISSUE TITLE
Rice 8.5: Maximum Likelihood 

### ISSUE THREAD

**Issue by stephramos17** [AmherstCollege/STAT370-Spring16#9]
So after reading 8.5 I have come to somewhat understand how we find maximum likelihood values. However, I guess I am still confused as to how we got the actual likelihood equation in the first place. Like why is the likelihood defined as the joint density of random variables X1,..,Xn and how does multiplying the marginal densities get you to this joint density? (Rice p.267-268)

**Comment by nicholasjhorton** [comment]
For both the MLE and the Bayesian methods, we need to specify the likelihood.  This is why we call such methods "parametric": we've specified a particular parametric form for the random variables.
